name: tiscamera-incuvers # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.2+git' # just for humans, typically '1.2+git' or '1.3.2'
summary: The Linux SDK for The Imaging Source cameras.
description: |
  The Linux SDK for The Imaging Source cameras. This snap is
  intended to facilitate the use of TIS cameras on Raspberry Pi
  IoT devices.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  tis:
    source-type: git
    source: https://github.com/TheImagingSource/tiscamera
    plugin: cmake

    build-packages:
            - git
            - g++
            - pkg-config
            - uuid-dev
            - libudev-dev
            - libgstreamer1.0-dev
            - libgstreamer1.0-0
            - libgstreamer-plugins-base1.0-dev
            - libglib2.0-dev
            - libgirepository1.0-dev
            - libusb-1.0-0-dev
            - libzip-dev
            - python3-setuptools
            - libusb-1.0-0
    stage-packages:
            - libusb-1.0-0
            - libgstreamer1.0-0
            - libgstreamer-plugins-base1.0-0
            - liborc-0.4-0
            - libpcre2-8-0
